package dev.mintu.hotseat.ui.art

// generated by tools/iso-art.mjs, do not edit by hand

object IsoScenes {
    val Hotseat = IsoScene(
        -171.88f, -157.6f, 416.51f, 357.2f,
        listOf(
            IsoPart("floor", 0f, 0f, listOf(
                IsoShape("M228.63,93.6L72.75,183.6L72.75,174L228.63,84Z", 0xFFCFE0F8, 1.2f),
                IsoShape("M-155.88,51.6L72.75,183.6L72.75,174L-155.88,42Z", 0xFFB6CFF3, 1.2f),
                IsoShape("M0,-48L228.63,84L72.75,174L-155.88,42Z", 0xFFEAF2FD, 1.2f),
            )),
            IsoPart("ring", 0f, 0f, listOf(
                IsoShape("M-64.66,36A64.66,37.33 0 1 0 64.66,36A64.66,37.33 0 1 0 -64.66,36Z", null, 1.6f, dashed = true),
            )),
            IsoPart("chair", 0f, 36f, listOf(
                IsoShape("M5.2,9L0,12L0,-21.6L5.2,-24.6Z", 0xFF2E2E2E, 1.4f),
                IsoShape("M-5.2,9L0,12L0,-21.6L-5.2,-24.6Z", 0xFF1C1C1C, 1.4f),
                IsoShape("M0,-27.6L5.2,-24.6L0,-21.6L-5.2,-24.6Z", 0xFF4A4A4A, 1.4f),
                IsoShape("M51.96,36L46.77,39L46.77,5.4L51.96,2.4Z", 0xFF2E2E2E, 1.4f),
                IsoShape("M41.57,36L46.77,39L46.77,5.4L41.57,2.4Z", 0xFF1C1C1C, 1.4f),
                IsoShape("M46.77,-0.6L51.96,2.4L46.77,5.4L41.57,2.4Z", 0xFF4A4A4A, 1.4f),
                IsoShape("M-41.57,36L-46.77,39L-46.77,5.4L-41.57,2.4Z", 0xFF2E2E2E, 1.4f),
                IsoShape("M-51.96,36L-46.77,39L-46.77,5.4L-51.96,2.4Z", 0xFF1C1C1C, 1.4f),
                IsoShape("M-46.77,-0.6L-41.57,2.4L-46.77,5.4L-51.96,2.4Z", 0xFF4A4A4A, 1.4f),
                IsoShape("M5.2,63L0,66L0,32.4L5.2,29.4Z", 0xFF2E2E2E, 1.4f),
                IsoShape("M-5.2,63L0,66L0,32.4L-5.2,29.4Z", 0xFF1C1C1C, 1.4f),
                IsoShape("M0,26.4L5.2,29.4L0,32.4L-5.2,29.4Z", 0xFF4A4A4A, 1.4f),
                IsoShape("M62.35,2.4L0,38.4L0,26.4L62.35,-9.6Z", 0xFF7DB0F5, 1.4f),
                IsoShape("M-62.35,2.4L0,38.4L0,26.4L-62.35,-9.6Z", 0xFF4989E9, 1.4f),
                IsoShape("M0,-45.6L62.35,-9.6L0,26.4L-62.35,-9.6Z", 0xFFCFE2FC, 1.4f),
                IsoShape("M50.92,-5.4L7.27,19.8L7.27,13.8L50.92,-11.4Z", 0xFFE6EDF7, 1.2f),
                IsoShape("M-40.53,-7.8L7.27,19.8L7.27,13.8L-40.53,-13.8Z", 0xFFCCD8E8, 1.2f),
                IsoShape("M3.12,-39L50.92,-11.4L7.27,13.8L-40.53,-13.8Z", 0xFFFFFFFF, 1.2f),
                IsoShape("M62.35,-9.6L54.04,-4.8L54.04,-24L62.35,-28.8Z", 0xFF7DB0F5, 1.4f),
                IsoShape("M2.08,-34.8L54.04,-4.8L54.04,-24L2.08,-54Z", 0xFF4989E9, 1.4f),
                IsoShape("M10.39,-58.8L62.35,-28.8L54.04,-24L2.08,-54Z", 0xFFCFE2FC, 1.4f),
                IsoShape("M12.47,-38.4L-49.88,-2.4L-49.88,-57.6L12.47,-93.6Z", 0xFF7DB0F5, 1.4f),
                IsoShape("M-62.35,-9.6L-49.88,-2.4L-49.88,-57.6L-62.35,-64.8Z", 0xFF4989E9, 1.4f),
                IsoShape("M0,-100.8L12.47,-93.6L-49.88,-57.6L-62.35,-64.8Z", 0xFFCFE2FC, 1.4f),
                IsoShape("M8.31,21.6L0,26.4L0,7.2L8.31,2.4Z", 0xFF7DB0F5, 1.4f),
                IsoShape("M-51.96,-3.6L0,26.4L0,7.2L-51.96,-22.8Z", 0xFF4989E9, 1.4f),
                IsoShape("M-43.65,-27.6L8.31,2.4L0,7.2L-51.96,-22.8Z", 0xFFCFE2FC, 1.4f),
            )),
            IsoPart("table", 83.14f, 104.4f, listOf(
                IsoShape("M110.16,104.4L83.14,120L83.14,115.2L110.16,99.6Z", 0xFFE6EDF7, 1.4f),
                IsoShape("M56.12,104.4L83.14,120L83.14,115.2L56.12,99.6Z", 0xFFCCD8E8, 1.4f),
                IsoShape("M83.14,84L110.16,99.6L83.14,115.2L56.12,99.6Z", 0xFFFFFFFF, 1.4f),
                IsoShape("M93.53,99.6L83.14,105.6L83.14,62.4L93.53,56.4Z", 0xFFE6EDF7, 1.4f),
                IsoShape("M72.75,99.6L83.14,105.6L83.14,62.4L72.75,56.4Z", 0xFFCCD8E8, 1.4f),
                IsoShape("M83.14,50.4L93.53,56.4L83.14,62.4L72.75,56.4Z", 0xFFFFFFFF, 1.4f),
                IsoShape("M149.65,56.4L83.14,94.8L83.14,87.6L149.65,49.2Z", 0xFFE6EDF7, 1.4f),
                IsoShape("M16.63,56.4L83.14,94.8L83.14,87.6L16.63,49.2Z", 0xFFCCD8E8, 1.4f),
                IsoShape("M83.14,10.8L149.65,49.2L83.14,87.6L16.63,49.2Z", 0xFFFFFFFF, 1.4f),
            )),
            IsoPart("bar0", 102.88f, 37.8f, listOf(
                IsoShape("M111.2,37.8L102.88,42.6L102.88,21L111.2,16.2Z", 0xFF7DB0F5, 1.2f),
                IsoShape("M94.57,37.8L102.88,42.6L102.88,21L94.57,16.2Z", 0xFF4989E9, 1.2f),
                IsoShape("M102.88,11.4L111.2,16.2L102.88,21L94.57,16.2Z", 0xFFCFE2FC, 1.2f),
            )),
            IsoPart("bar1", 90.41f, 45f, listOf(
                IsoShape("M98.73,45L90.41,49.8L90.41,6.6L98.73,1.8Z", 0xFFE03143, 1.2f),
                IsoShape("M82.1,45L90.41,49.8L90.41,6.6L82.1,1.8Z", 0xFFB81F31, 1.2f),
                IsoShape("M90.41,-3L98.73,1.8L90.41,6.6L82.1,1.8Z", 0xFFF27A86, 1.2f),
            )),
            IsoPart("bar2", 77.94f, 52.2f, listOf(
                IsoShape("M86.26,52.2L77.94,57L77.94,25.8L86.26,21Z", 0xFF7DB0F5, 1.2f),
                IsoShape("M69.63,52.2L77.94,57L77.94,25.8L69.63,21Z", 0xFF4989E9, 1.2f),
                IsoShape("M77.94,16.2L86.26,21L77.94,25.8L69.63,21Z", 0xFFCFE2FC, 1.2f),
            )),
            IsoPart("bar3", 65.47f, 59.4f, listOf(
                IsoShape("M73.79,59.4L65.47,64.2L65.47,47.4L73.79,42.6Z", 0xFF7DB0F5, 1.2f),
                IsoShape("M57.16,59.4L65.47,64.2L65.47,47.4L57.16,42.6Z", 0xFF4989E9, 1.2f),
                IsoShape("M65.47,37.8L73.79,42.6L65.47,47.4L57.16,42.6Z", 0xFFCFE2FC, 1.2f),
            )),
            IsoPart("trail", 70.67f, -34.8f, listOf(
                IsoShape("M80.02,-28.2L72.75,-24L72.75,-32.4L80.02,-36.6Z", 0xFFE6EDF7, 1.1f),
                IsoShape("M65.47,-28.2L72.75,-24L72.75,-32.4L65.47,-36.6Z", 0xFFCCD8E8, 1.1f),
                IsoShape("M72.75,-40.8L80.02,-36.6L72.75,-32.4L65.47,-36.6Z", 0xFFFFFFFF, 1.1f),
                IsoShape("M81.06,-49.2L70.67,-43.2L70.67,-55.2L81.06,-61.2Z", 0xFFE6EDF7, 1.2f),
                IsoShape("M60.28,-49.2L70.67,-43.2L70.67,-55.2L60.28,-61.2Z", 0xFFCCD8E8, 1.2f),
                IsoShape("M70.67,-67.2L81.06,-61.2L70.67,-55.2L60.28,-61.2Z", 0xFFFFFFFF, 1.2f),
            )),
            IsoPart("bubble", 103.92f, -84f, listOf(
                IsoShape("M166.28,-78L114.32,-48L114.32,-57.6L166.28,-87.6Z", 0xFFE6EDF7, 1.4f),
                IsoShape("M41.57,-90L114.32,-48L114.32,-57.6L41.57,-99.6Z", 0xFFCCD8E8, 1.4f),
                IsoShape("M93.53,-129.6L166.28,-87.6L114.32,-57.6L41.57,-99.6Z", 0xFFFFFFFF, 1.4f),
                IsoShape("M80.99,-102.6A7.35,4.24 0 1 0 95.68,-102.6A7.35,4.24 0 1 0 80.99,-102.6Z", 0xFF1C1C1C, 0f),
                IsoShape("M96.57,-93.6A7.35,4.24 0 1 0 111.27,-93.6A7.35,4.24 0 1 0 96.57,-93.6Z", 0xFF1C1C1C, 0f),
                IsoShape("M112.16,-84.6A7.35,4.24 0 1 0 126.86,-84.6A7.35,4.24 0 1 0 112.16,-84.6Z", 0xFF1C1C1C, 0f),
            )),
        ),
    )

    val Sessions = IsoScene(
        -161.49f, -64f, 364.55f, 245.6f,
        listOf(
            IsoPart("floor", 0f, 0f, listOf(
                IsoShape("M187.06,81.6L41.57,165.6L41.57,156L187.06,72Z", 0xFFCFE0F8, 1.2f),
                IsoShape("M-145.49,57.6L41.57,165.6L41.57,156L-145.49,48Z", 0xFFB6CFF3, 1.2f),
                IsoShape("M0,-36L187.06,72L41.57,156L-145.49,48Z", 0xFFEAF2FD, 1.2f),
            )),
            IsoPart("card0", 20.78f, 60f, listOf(
                IsoShape("M124.71,72L41.57,120L41.57,110.4L124.71,62.4Z", 0xFFE6EDF7, 1.4f),
                IsoShape("M-83.14,48L41.57,120L41.57,110.4L-83.14,38.4Z", 0xFFCCD8E8, 1.4f),
                IsoShape("M0,-9.6L124.71,62.4L41.57,110.4L-83.14,38.4Z", 0xFFFFFFFF, 1.4f),
            )),
            IsoPart("card1", 20.78f, 56.4f, listOf(
                IsoShape("M124.71,68.4L41.57,116.4L41.57,106.8L124.71,58.8Z", 0xFFE6EDF7, 1.4f),
                IsoShape("M-83.14,44.4L41.57,116.4L41.57,106.8L-83.14,34.8Z", 0xFFCCD8E8, 1.4f),
                IsoShape("M0,-13.2L124.71,58.8L41.57,106.8L-83.14,34.8Z", 0xFFFFFFFF, 1.4f),
            )),
            IsoPart("card2", 20.78f, 52.8f, listOf(
                IsoShape("M124.71,64.8L41.57,112.8L41.57,103.2L124.71,55.2Z", 0xFF7DB0F5, 1.4f),
                IsoShape("M-83.14,40.8L41.57,112.8L41.57,103.2L-83.14,31.2Z", 0xFF4989E9, 1.4f),
                IsoShape("M0,-16.8L124.71,55.2L41.57,103.2L-83.14,31.2Z", 0xFFCFE2FC, 1.4f),
                IsoShape("M-10.29,7.2A10.29,5.94 0 1 0 10.29,7.2A10.29,5.94 0 1 0 -10.29,7.2Z", 0xFFE03143, 1.2f),
                IsoShape("M-33.26,26.4L-54.04,38.4L-25.98,42.6Z", 0xFF1C1C1C, 0f),
            )),
            IsoPart("wave0", 27.02f, 31.2f, listOf(
                IsoShape("M33.26,31.2L27.02,34.8L27.02,22.8L33.26,19.2Z", 0xFFE6EDF7, 1f),
                IsoShape("M20.78,31.2L27.02,34.8L27.02,22.8L20.78,19.2Z", 0xFFCCD8E8, 1f),
                IsoShape("M27.02,15.6L33.26,19.2L27.02,22.8L20.78,19.2Z", 0xFFFFFFFF, 1f),
            )),
            IsoPart("wave1", 38.45f, 37.8f, listOf(
                IsoShape("M44.69,37.8L38.45,41.4L38.45,17.4L44.69,13.8Z", 0xFFE6EDF7, 1f),
                IsoShape("M32.22,37.8L38.45,41.4L38.45,17.4L32.22,13.8Z", 0xFFCCD8E8, 1f),
                IsoShape("M38.45,10.2L44.69,13.8L38.45,17.4L32.22,13.8Z", 0xFFFFFFFF, 1f),
            )),
            IsoPart("wave2", 49.88f, 44.4f, listOf(
                IsoShape("M56.12,44.4L49.88,48L49.88,12L56.12,8.4Z", 0xFFE6EDF7, 1f),
                IsoShape("M43.65,44.4L49.88,48L49.88,12L43.65,8.4Z", 0xFFCCD8E8, 1f),
                IsoShape("M49.88,4.8L56.12,8.4L49.88,12L43.65,8.4Z", 0xFFFFFFFF, 1f),
            )),
            IsoPart("wave3", 61.31f, 51f, listOf(
                IsoShape("M67.55,51L61.31,54.6L61.31,35.4L67.55,31.8Z", 0xFFE6EDF7, 1f),
                IsoShape("M55.08,51L61.31,54.6L61.31,35.4L55.08,31.8Z", 0xFFCCD8E8, 1f),
                IsoShape("M61.31,28.2L67.55,31.8L61.31,35.4L55.08,31.8Z", 0xFFFFFFFF, 1f),
            )),
            IsoPart("wave4", 72.75f, 57.6f, listOf(
                IsoShape("M78.98,57.6L72.75,61.2L72.75,30L78.98,26.4Z", 0xFFE6EDF7, 1f),
                IsoShape("M66.51,57.6L72.75,61.2L72.75,30L66.51,26.4Z", 0xFFCCD8E8, 1f),
                IsoShape("M72.75,22.8L78.98,26.4L72.75,30L66.51,26.4Z", 0xFFFFFFFF, 1f),
            )),
            IsoPart("wave5", 84.18f, 64.2f, listOf(
                IsoShape("M90.41,64.2L84.18,67.8L84.18,53.4L90.41,49.8Z", 0xFFE6EDF7, 1f),
                IsoShape("M77.94,64.2L84.18,67.8L84.18,53.4L77.94,49.8Z", 0xFFCCD8E8, 1f),
                IsoShape("M84.18,46.2L90.41,49.8L84.18,53.4L77.94,49.8Z", 0xFFFFFFFF, 1f),
            )),
        ),
    )

    val Progress = IsoScene(
        -130.32f, -125.8f, 333.38f, 295.4f,
        listOf(
            IsoPart("floor", 0f, 0f, listOf(
                IsoShape("M187.06,81.6L62.35,153.6L62.35,144L187.06,72Z", 0xFFCFE0F8, 1.2f),
                IsoShape("M-114.32,51.6L62.35,153.6L62.35,144L-114.32,42Z", 0xFFB6CFF3, 1.2f),
                IsoShape("M10.39,-30L187.06,72L62.35,144L-114.32,42Z", 0xFFEAF2FD, 1.2f),
            )),
            IsoPart("step0", -18.71f, 25.2f, listOf(
                IsoShape("M24.94,14.4L-37.41,50.4L-37.41,31.2L24.94,-4.8Z", 0xFFE6EDF7, 1.4f),
                IsoShape("M-62.35,36L-37.41,50.4L-37.41,31.2L-62.35,16.8Z", 0xFFCCD8E8, 1.4f),
                IsoShape("M0,-19.2L24.94,-4.8L-37.41,31.2L-62.35,16.8Z", 0xFFFFFFFF, 1.4f),
            )),
            IsoPart("step1", 6.24f, 39.6f, listOf(
                IsoShape("M49.88,28.8L-12.47,64.8L-12.47,24L49.88,-12Z", 0xFFE6EDF7, 1.4f),
                IsoShape("M-37.41,50.4L-12.47,64.8L-12.47,24L-37.41,9.6Z", 0xFFCCD8E8, 1.4f),
                IsoShape("M24.94,-26.4L49.88,-12L-12.47,24L-37.41,9.6Z", 0xFFFFFFFF, 1.4f),
            )),
            IsoPart("step2", 31.18f, 54f, listOf(
                IsoShape("M74.82,43.2L12.47,79.2L12.47,16.8L74.82,-19.2Z", 0xFFE6EDF7, 1.4f),
                IsoShape("M-12.47,64.8L12.47,79.2L12.47,16.8L-12.47,2.4Z", 0xFFCCD8E8, 1.4f),
                IsoShape("M49.88,-33.6L74.82,-19.2L12.47,16.8L-12.47,2.4Z", 0xFFFFFFFF, 1.4f),
            )),
            IsoPart("step3", 56.12f, 68.4f, listOf(
                IsoShape("M99.77,57.6L37.41,93.6L37.41,9.6L99.77,-26.4Z", 0xFFE6EDF7, 1.4f),
                IsoShape("M12.47,79.2L37.41,93.6L37.41,9.6L12.47,-4.8Z", 0xFFCCD8E8, 1.4f),
                IsoShape("M74.82,-40.8L99.77,-26.4L37.41,9.6L12.47,-4.8Z", 0xFFFFFFFF, 1.4f),
            )),
            IsoPart("step4", 81.06f, 82.8f, listOf(
                IsoShape("M124.71,72L62.35,108L62.35,2.4L124.71,-33.6Z", 0xFF7DB0F5, 1.4f),
                IsoShape("M37.41,93.6L62.35,108L62.35,2.4L37.41,-12Z", 0xFF4989E9, 1.4f),
                IsoShape("M99.77,-48L124.71,-33.6L62.35,2.4L37.41,-12Z", 0xFFCFE2FC, 1.4f),
            )),
            IsoPart("flag", 96.65f, -33f, listOf(
                IsoShape("M100.29,-33.3L96.65,-31.2L96.65,-93.6L100.29,-95.7Z", 0xFF2E2E2E, 1f),
                IsoShape("M93.01,-33.3L96.65,-31.2L96.65,-93.6L93.01,-95.7Z", 0xFF1C1C1C, 1f),
                IsoShape("M96.65,-97.8L100.29,-95.7L96.65,-93.6L93.01,-95.7Z", 0xFF4A4A4A, 1f),
                IsoShape("M127.31,-56.1L124.19,-54.3L124.19,-75.9L127.31,-77.7Z", 0xFFE03143, 1.2f),
                IsoShape("M97.17,-69.9L124.19,-54.3L124.19,-75.9L97.17,-91.5Z", 0xFFB81F31, 1.2f),
                IsoShape("M100.29,-93.3L127.31,-77.7L124.19,-75.9L97.17,-91.5Z", 0xFFF27A86, 1.2f),
            )),
        ),
    )

    val You = IsoScene(
        -151.1f, -64f, 343.77f, 233.6f,
        listOf(
            IsoPart("floor", 0f, 0f, listOf(
                IsoShape("M176.67,75.6L41.57,153.6L41.57,144L176.67,66Z", 0xFFCFE0F8, 1.2f),
                IsoShape("M-135.1,51.6L41.57,153.6L41.57,144L-135.1,42Z", 0xFFB6CFF3, 1.2f),
                IsoShape("M0,-36L176.67,66L41.57,144L-135.1,42Z", 0xFFEAF2FD, 1.2f),
            )),
            IsoPart("badge", 15.59f, 57f, listOf(
                IsoShape("M114.32,66L31.18,114L31.18,104.4L114.32,56.4Z", 0xFFE6EDF7, 1.4f),
                IsoShape("M-83.14,48L31.18,114L31.18,104.4L-83.14,38.4Z", 0xFFCCD8E8, 1.4f),
                IsoShape("M0,-9.6L114.32,56.4L31.18,104.4L-83.14,38.4Z", 0xFFFFFFFF, 1.4f),
                IsoShape("M-37.71,33.6A29.39,16.97 0 1 0 21.08,33.6A29.39,16.97 0 1 0 -37.71,33.6Z", 0xFF4989E9, 1.4f),
                IsoShape("M-20.07,26.4A11.76,6.79 0 1 0 3.44,26.4A11.76,6.79 0 1 0 -20.07,26.4Z", 0xFFCFE2FC, 1.1f),
                IsoShape("M81.06,63.6L72.75,68.4L72.75,64.8L81.06,60Z", 0xFF7DB0F5, 1f),
                IsoShape("M31.18,44.4L72.75,68.4L72.75,64.8L31.18,40.8Z", 0xFF4989E9, 1f),
                IsoShape("M39.49,36L81.06,60L72.75,64.8L31.18,40.8Z", 0xFFCFE2FC, 1f),
                IsoShape("M51.96,68.4L43.65,73.2L43.65,69.6L51.96,64.8Z", 0xFFE6EDF7, 1f),
                IsoShape("M12.47,55.2L43.65,73.2L43.65,69.6L12.47,51.6Z", 0xFFCCD8E8, 1f),
                IsoShape("M20.78,46.8L51.96,64.8L43.65,69.6L12.47,51.6Z", 0xFFFFFFFF, 1f),
                IsoShape("M41.57,81.6L33.26,86.4L33.26,82.8L41.57,78Z", 0xFFE6EDF7, 1f),
                IsoShape("M-4.16,64.8L33.26,86.4L33.26,82.8L-4.16,61.2Z", 0xFFCCD8E8, 1f),
                IsoShape("M4.16,56.4L41.57,78L33.26,82.8L-4.16,61.2Z", 0xFFFFFFFF, 1f),
            )),
            IsoPart("check", 83.14f, 55.2f, listOf(
                IsoShape("M69.91,55.2A13.23,7.64 0 1 0 96.37,55.2A13.23,7.64 0 1 0 69.91,55.2Z", 0xFFE03143, 1.2f),
            )),
        ),
    )
}
