package dev.mintu.hotseat.ui.brand

// generated by tools/brand.mjs, do not edit by hand

object Brand {
    const val CHAIR = "M7,3.5V20.5M7,12.5H13.2C15.3,12.5 16.5,13.7 16.5,15.8V20.5"
    const val STROKE = 3.4f
    const val DOT_X = 16.2f
    const val DOT_Y = 6.4f
    const val DOT_R = 2.5f
    const val SKY_TOP = 0xFF6793DF
    const val SKY_BOTTOM = 0xFF4989E9
}
