package dev.mintu.hotseat.ui.brand

// generated by tools/mascot.mjs, do not edit by hand

object MascotArt {
    const val BOX = 512f

    val shapes = listOf(
        MascotShape("wingL", "M118.83,309.23A36,62 14 1 0 188.69,326.64A36,62 14 1 0 118.83,309.23Z", 0xFF3B7BEF, 0xFF141210, 12f),
        MascotShape("wingR", "M323.31,326.64A36,62 -14 1 0 393.17,309.23A36,62 -14 1 0 323.31,326.64Z", 0xFF3B7BEF, 0xFF141210, 12f),
        MascotShape("feet", "M232,404V430M280,404V430M220,430H244M268,430H292", null, 0xFF141210, 10f),
        MascotShape("body", "M120,282A136,128 0 1 0 392,282A136,128 0 1 0 120,282Z", 0xFF3B7BEF, 0xFF141210, 12f),
        MascotShape("face", "M160,276A96,86 0 1 0 352,276A96,86 0 1 0 160,276Z", 0xFFFFFFFF, null, 0f),
        MascotShape("eyes", "", null, null, 0f),
        MascotShape("cheeks", "M181,298A15,9 0 1 0 211,298A15,9 0 1 0 181,298ZM301,298A15,9 0 1 0 331,298A15,9 0 1 0 301,298Z", 0x80E03143, null, 0f),
        MascotShape("beak", "M234,284Q256,274 278,284Q266,314 256,316Q246,314 234,284Z", 0xFFFFB23E, 0xFF141210, 8f),
        MascotShape("band", "M120,262C120,100 392,100 392,262", null, 0xFF141210, 18f),
        MascotShape("cups", "M116,226H120A20,20 0 0 1 140,246V288A20,20 0 0 1 120,308H116A20,20 0 0 1 96,288V246A20,20 0 0 1 116,226ZM392,226H396A20,20 0 0 1 416,246V288A20,20 0 0 1 396,308H392A20,20 0 0 1 372,288V246A20,20 0 0 1 392,226Z", 0xFF141210, null, 0f),
        MascotShape("arm", "M394,300C398,352 360,372 318,366", null, 0xFF141210, 10f),
        MascotShape("mic", "M294,366A16,16 0 1 0 326,366A16,16 0 1 0 294,366Z", 0xFFE03143, 0xFF141210, 8f),
    )

    const val WING_L_X = 146f
    const val WING_L_Y = 262f
    const val WING_R_X = 366f
    const val WING_R_Y = 262f

    const val EYE_L = 222f
    const val EYE_R = 290f
    const val EYE_Y = 250f
    const val EYE_W = 20f
    const val EYE_H = 24f
    const val CATCHLIGHT = 7f
    const val EYE_INK = 0xFF0F0C07

    const val MIC_X = 310f
    const val MIC_Y = 366f

    const val STICKER_CX = 256f
    const val STICKER_CY = 266f
    const val STICKER_RX = 204f
    const val STICKER_RY = 206f
    const val STICKER_GLOW_X = 256f
    const val STICKER_GLOW_Y = 248f
    const val STICKER_GLOW_R = 212f
    const val PAPER = 0xFFE6EBFF

    // the splash drawable is 108 units shown at 288dp, this is how big the 512 box ends up on screen
    const val SPLASH_BOX_DP = 232.11f
    const val SKY_TOP = 0xFF6793DF
    const val SKY_BOTTOM = 0xFF4989E9
}
