// the hotseat mark: a rounded lowercase h that is also a chair seen from the side, with a red dot about to sit
// writes the svgs for web, the android launcher and splash drawables, and Brand.kt
// usage: node tools/brand.mjs
import { writeFileSync, mkdirSync } from "node:fs"

const sky = { top: "#6793DF", bottom: "#4989E9" }
const red = "#E03143"
const ink = "#1C1C1C"

// on a 24 grid: backrest, seat running into the front leg, and the dot
const chair = "M7,3.5V20.5M7,12.5H13.2C15.3,12.5 16.5,13.7 16.5,15.8V20.5"
const stroke = 3.4
const dot = { cx: 16.2, cy: 6.4, r: 2.5 }

const svg = (w, body, extra = "") => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${w}" width="${w}" height="${w}"${extra}>\n${body}\n</svg>\n`
const markBody = (color, dotColor) =>
  `  <path d="${chair}" fill="none" stroke="${color}" stroke-width="${stroke}" stroke-linecap="round" stroke-linejoin="round"/>\n` +
  `  <circle cx="${dot.cx}" cy="${dot.cy}" r="${dot.r}" fill="${dotColor}"/>`

// the tile scales the 24 grid mark into a 108 canvas, inside the 66 unit adaptive icon safe zone
const scale = 2.3
const offset = +(54 - 12 * scale).toFixed(2)
const tileBody = (size) => {
  const k = size / 108
  return `  <defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${sky.top}"/><stop offset="1" stop-color="${sky.bottom}"/></linearGradient></defs>\n` +
    `  <rect width="${size}" height="${size}" rx="${24 * k}" fill="url(#g)"/>\n` +
    `  <g transform="translate(${offset * k} ${offset * k}) scale(${scale * k})">\n  ${markBody("#FFFFFF", red).replace(/\n/g, "\n  ")}\n  </g>`
}

mkdirSync("docs/brand", { recursive: true })
writeFileSync("docs/brand/mark.svg", svg(24, markBody(ink, red)))
writeFileSync("docs/brand/mark-white.svg", svg(24, markBody("#FFFFFF", red)))
writeFileSync("docs/brand/icon.svg", svg(108, tileBody(108)))
writeFileSync("docs/brand/favicon.svg", svg(32, tileBody(32)))

const res = "android/app/src/main/res"
mkdirSync(`${res}/drawable`, { recursive: true })
mkdirSync(`${res}/mipmap-anydpi-v26`, { recursive: true })

const group = (inner) => `    <group android:translateX="${offset}" android:translateY="${offset}" android:scaleX="${scale}" android:scaleY="${scale}">\n${inner}\n    </group>`
const vecPath = (color) => `        <path android:pathData="${chair}" android:strokeColor="${color}" android:strokeWidth="${stroke}" android:strokeLineCap="round" android:strokeLineJoin="round" />`
const vecDot = (color) => `        <path android:pathData="M${dot.cx - dot.r},${dot.cy}a${dot.r},${dot.r} 0 1,0 ${dot.r * 2},0a${dot.r},${dot.r} 0 1,0 ${-dot.r * 2},0" android:fillColor="${color}" />`
const vector = (inner) => `<vector xmlns:android="http://schemas.android.com/apk/res/android"\n    android:width="108dp"\n    android:height="108dp"\n    android:viewportWidth="108"\n    android:viewportHeight="108">\n${inner}\n</vector>\n`

writeFileSync(`${res}/drawable/ic_launcher_foreground.xml`, vector(group(vecPath("#FFFFFF") + "\n" + vecDot(red))))
writeFileSync(`${res}/drawable/ic_launcher_monochrome.xml`, vector(group(vecPath("#000000") + "\n" + vecDot("#000000"))))
writeFileSync(`${res}/drawable/ic_launcher_background.xml`, `<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path android:pathData="M0,0h108v108h-108z">
        <aapt:attr name="android:fillColor">
            <gradient android:type="linear" android:startX="54" android:startY="0" android:endX="54" android:endY="108">
                <item android:offset="0" android:color="${sky.top.replace("#", "#FF")}" />
                <item android:offset="1" android:color="${sky.bottom.replace("#", "#FF")}" />
            </gradient>
        </aapt:attr>
    </path>
</vector>
`)
const adaptive = `<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
`
writeFileSync(`${res}/mipmap-anydpi-v26/ic_launcher.xml`, adaptive)
writeFileSync(`${res}/mipmap-anydpi-v26/ic_launcher_round.xml`, adaptive)

writeFileSync("android/app/src/main/java/dev/mintu/hotseat/ui/brand/Brand.kt", `package dev.mintu.hotseat.ui.brand

// generated by tools/brand.mjs, do not edit by hand

object Brand {
    const val CHAIR = "${chair}"
    const val STROKE = ${stroke}f
    const val DOT_X = ${dot.cx}f
    const val DOT_Y = ${dot.cy}f
    const val DOT_R = ${dot.r}f
    const val SKY_TOP = 0xFF${sky.top.slice(1)}
    const val SKY_BOTTOM = 0xFF${sky.bottom.slice(1)}
}
`)
console.log("wrote docs/brand, launcher drawables, Brand.kt")
