// turns nucleo glass svgs into GlassIcons.kt
// usage: node tools/glass-icons.mjs <glass dir> <out.kt> name[:KotlinName] ...
import { readFileSync, writeFileSync } from "node:fs"

const [dir, out, ...names] = process.argv.slice(2)

const attr = (tag, name) => tag.match(new RegExp(`\\s${name}="([^"]*)"`))?.[1]

function toPath(tag) {
  if (tag.startsWith("<path")) return attr(tag, "d")
  if (tag.startsWith("<rect")) {
    const x = +attr(tag, "x") || 0, y = +attr(tag, "y") || 0
    const w = +attr(tag, "width"), h = +attr(tag, "height"), r = +(attr(tag, "rx") ?? 0)
    return `M${x + r},${y}H${x + w - r}A${r},${r} 0 0 1 ${x + w},${y + r}V${y + h - r}A${r},${r} 0 0 1 ${x + w - r},${y + h}H${x + r}A${r},${r} 0 0 1 ${x},${y + h - r}V${y + r}A${r},${r} 0 0 1 ${x + r},${y}Z`
  }
  if (tag.startsWith("<circle")) {
    const cx = +attr(tag, "cx"), cy = +attr(tag, "cy"), r = +attr(tag, "r")
    return `M${cx - r},${cy}A${r},${r} 0 1 0 ${cx + r},${cy}A${r},${r} 0 1 0 ${cx - r},${cy}Z`
  }
  throw new Error("unsupported element " + tag.slice(0, 20))
}

function gradient(svg, id) {
  const m = svg.match(new RegExp(`<linearGradient id="${id}"([^>]*)>([\\s\\S]*?)</linearGradient>`))
  if (!m) throw new Error("missing gradient " + id)
  const stops = [...m[2].matchAll(/<stop([^>]*)>/g)].map(([, a]) => {
    const offset = +(attr(a, "offset") ?? 0)
    let hex = attr(a, "stop-color").replace("#", "")
    if (hex.length === 3) hex = [...hex].map((c) => c + c).join("")
    const alpha = Math.round(+(attr(a, "stop-opacity") ?? 1) * 255)
    return `${offset}f to 0x${alpha.toString(16).padStart(2, "0").toUpperCase()}${hex.toUpperCase()}`
  })
  const n = (k) => `${+attr(m[1], k)}f`
  return `Grad(${n("x1")}, ${n("y1")}, ${n("x2")}, ${n("y2")}, listOf(${stops.join(", ")}))`
}

const icons = names.map((spec) => {
  const [file, kt = file.replace(/(^|-)(\w)/g, (_, __, c) => c.toUpperCase())] = spec.split(":")
  const svg = readFileSync(`${dir}/${file}.svg`, "utf8")
  const body = svg.split("<defs>")[0]
  const tags = [...body.matchAll(/<(path|rect|circle)\b[^>]*>/g)].map((m) => m[0])
  const fillId = (t) => attr(t, "fill").match(/url\(#(.*)\)/)[1]
  const back = tags.find((t) => attr(t, "data-glass") === "origin")
  const front = tags.find((t) => attr(t, "data-glass") === "blur") ?? tags.find((t) => !attr(t, "data-glass"))
  const rims = tags.filter((t) => !attr(t, "data-glass") && t !== front)
  const blur = +(svg.match(/stdDeviation="([^"]*)"/)?.[1] ?? 2)
  const layer = (t) => `Layer("${toPath(t)}", ${gradient(svg, fillId(t))}${attr(t, "fill-rule") === "evenodd" ? ", evenOdd = true" : ""})`
  return `    val ${kt} = GlassIcon(\n        back = ${layer(back)},\n        front = ${layer(front)},\n        rims = listOf(${rims.map(layer).join(", ")}),\n        blur = ${blur}f,\n    )`
})

writeFileSync(out, `package dev.mintu.hotseat.ui.icons

// generated by tools/glass-icons.mjs from the nucleo glass set, do not edit by hand

object GlassIcons {
${icons.join("\n\n")}
}
`)
console.log("wrote", out, icons.length, "icons")
