// turns nucleo micro-bold svgs into InkIcons.kt
// usage: node tools/ink-icons.mjs <icon dir> <out.kt> name[:KotlinName] ...
import { readFileSync, writeFileSync } from "node:fs"

const [dir, out, ...names] = process.argv.slice(2)
const attr = (tag, name) => tag.match(new RegExp(`\\s${name}="([^"]*)"`))?.[1]
const nums = (s) => s.trim().split(/[\s,]+/).map(Number)

function toPath(tag) {
  const el = tag.match(/^<(\w+)/)[1]
  if (el === "path") return attr(tag, "d")
  if (el === "line") return `M${attr(tag, "x1")},${attr(tag, "y1")}L${attr(tag, "x2")},${attr(tag, "y2")}`
  if (el === "polyline" || el === "polygon") {
    const p = nums(attr(tag, "points"))
    let d = `M${p[0]},${p[1]}`
    for (let i = 2; i < p.length; i += 2) d += `L${p[i]},${p[i + 1]}`
    return el === "polygon" ? d + "Z" : d
  }
  if (el === "rect") {
    const x = +(attr(tag, "x") ?? 0), y = +(attr(tag, "y") ?? 0), w = +attr(tag, "width"), h = +attr(tag, "height")
    const r = Math.min(+(attr(tag, "rx") ?? attr(tag, "ry") ?? 0), w / 2, h / 2)
    if (!r) return `M${x},${y}H${x + w}V${y + h}H${x}Z`
    return `M${x + r},${y}H${x + w - r}A${r},${r} 0 0 1 ${x + w},${y + r}V${y + h - r}A${r},${r} 0 0 1 ${x + w - r},${y + h}H${x + r}A${r},${r} 0 0 1 ${x},${y + h - r}V${y + r}A${r},${r} 0 0 1 ${x + r},${y}Z`
  }
  if (el === "circle" || el === "ellipse") {
    const cx = +attr(tag, "cx"), cy = +attr(tag, "cy"), rx = +(attr(tag, "r") ?? attr(tag, "rx")), ry = +(attr(tag, "r") ?? attr(tag, "ry"))
    return `M${cx - rx},${cy}A${rx},${ry} 0 1 0 ${cx + rx},${cy}A${rx},${ry} 0 1 0 ${cx - rx},${cy}Z`
  }
  throw new Error("unsupported " + el)
}

const icons = names.map((spec) => {
  const [file, kt = file.replace(/(^|-)(\w)/g, (_, __, c) => c.toUpperCase())] = spec.split(":")
  const svg = readFileSync(`${dir}/${file}.svg`, "utf8")
  const view = nums(svg.match(/viewBox="([^"]*)"/)[1])[2]
  const tags = [...svg.matchAll(/<(path|line|polyline|polygon|rect|circle|ellipse)\b[^>]*>/g)].map((m) => m[0])
  const parts = tags.map((t) => {
    const stroke = attr(t, "stroke") && attr(t, "stroke") !== "none"
    const fill = attr(t, "fill") !== "none" && (attr(t, "fill") || !stroke)
    const args = [
      `"${toPath(t)}"`,
      `stroke = ${stroke ? +(attr(t, "stroke-width") ?? 1) + "f" : "0f"}`,
      `fill = ${!!fill}`,
    ]
    if (attr(t, "data-color") === "color-2") args.push("accent = true")
    if (attr(t, "stroke-linecap") === "square") args.push("square = true")
    if (attr(t, "fill-rule") === "evenodd") args.push("evenOdd = true")
    return `Part(${args.join(", ")})`
  })
  return `    val ${kt} = InkIcon(${view}f, listOf(\n        ${parts.join(",\n        ")},\n    ))`
})

writeFileSync(out, `package dev.mintu.hotseat.ui.icons

// generated by tools/ink-icons.mjs from the nucleo micro-bold set, do not edit by hand

object InkIcons {
${icons.join("\n\n")}
}
`)
console.log("wrote", out, icons.length, "icons")
